# Generated by Django 2.1 on 2019-03-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190320_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoentry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
