# Generated by Django 2.1 on 2019-03-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190320_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
