# Generated by Django 2.1 on 2019-03-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_details_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoentry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
